spring:
  profiles:
    active:
    - dev
---
server: 
  port: 8001
  
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://49.232.160.115:3306/cloudDB01?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: music_clown_mysql_48519
    dbcp2: 
      min-idle: 5                                          # 数据库连接池的最小维持连接数
      initial-size: 5                                      # 初始化连接数
      max-total: 5                                         # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取最大超时时间

mybatis: 
  config-location: classpath:mybatis/mybatis.cgf.xml       # mybatis配置文件的所在路径
  type-aliases-package: com.atguigu.springcloud.entity     # 所有Entity别名类所在包
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml                      # mapper映射文件

eureka: 
  client: # 客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: 
    instance-id: microservicecloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址
      
info: 
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
  port: 8001
  
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://49.232.160.115:3306/cloudDB02?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: music_clown_mysql_48519
    dbcp2: 
      min-idle: 5                                          # 数据库连接池的最小维持连接数
      initial-size: 5                                      # 初始化连接数
      max-total: 5                                         # 最大连接数
      max-wait-millis: 200                                 # 等待连接获取最大超时时间

mybatis: 
  config-location: classpath:mybatis/mybatis.cgf.xml       # mybatis配置文件的所在路径
  type-aliases-package: com.atguigu.springcloud.entity     # 所有Entity别名类所在包
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml                      # mapper映射文件

eureka: 
  client: # 客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance: 
    instance-id: microservicecloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址
      
info: 
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

  